### ISSUE TITLE
fragpipe to csv() function error

### ISSUE THREAD

**Issue by XueNotavailbale** [Nesvilab/FragPipe#1076]
Hi, I am running fragpipe 18.0 for a DIA analysis with spectral library building from DDA files. I think the data analysis has finished but the problem is at the csv export process. I have found 4 result files named peptide, protein, ion and psm tsv files seperatly. But the quantificaiton file seems to be missing. The reported error is "TypeError: to_csv() got an unexpected keyword argument 'line_terminator'". I have tried to remove "line_terminator='\n'  from "gen_con_spec_lib.py" file but it didn't work. But I do got en extra file named irt. tsv. 
How to fix this?
xueyang

-Process 'PhilosopherReport' finished, exit code: 0
SpecLibGen [Work dir: C:\Result\zxy\DIA-TMT\fragpipe_diaNN\230404_10]
C:\Users\Xue\AppData\Local\Programs\Python\Python39\python.exe -u C:\software\fragpipe\tools\speclib\gen_con_spec_lib.py C:\Result\databank\2023-04-04-decoys-contam-Ara_human_iRT.fasta C:\Result\zxy\DIA-TMT\fragpipe_diaNN\230404_10 unused C:\Result\zxy\DIA-TMT\fragpipe_diaNN\230404_10 True unused use_easypqp iRT;noIM 10 "--max_delta_unimod 0.02 --max_delta_ppm 15.0 --fragment_types [\'b\',\'y\',]" "--rt_lowess_fraction 0.0" delete_intermediate_files C:\Result\zxy\DIA-TMT\fragpipe_diaNN\230404_10\filelist_speclibgen.txt
File list provided
Process 'SpecLibGen' finished, exit code: 1
Traceback (most recent call last):
  File "C:\software\fragpipe\tools\speclib\gen_con_spec_lib.py", line 975, in <module>
    main_easypqp()
  File "C:\software\fragpipe\tools\speclib\gen_con_spec_lib.py", line 753, in main_easypqp
    irt_df.to_csv(irt_file, index=False, sep='\t', line_terminator='\n')
TypeError: to_csv() got an unexpected keyword argument 'line_terminator'
Process returned non-zero exit code, stopping

**Comment by fcyu** [comment]
Can you upgrade **all** of FragPipe, MSFragger, and Philosopher to the latest version and try again?

Thanks,

Fengchao

**Comment by fcyu** [comment]
That's correct. Could you upload the log file?

Thanks,

Fengchao

**Comment by XueNotavailbale** [comment]
[log_2023-04-11_13-36-43.txt](https://github.com/Nesvilab/FragPipe/files/11200398/log_2023-04-11_13-36-43.txt)
Here is the log file.

**Comment by fcyu** [comment]
Thanks for your file. What Python version are you using? Can you upgrade one of the library by running

```shell
pip install --upgrade pandas
```

Thanks,

Fengchao

**Comment by guoci** [comment]
fixed in https://github.com/Nesvilab/FragPipe/commit/c01d623d31848a17dbb66713212c15a897fdac24

**Comment by guoci** [comment]
yes

**Comment by XueNotavailbale** [comment]
> Thanks @guoci . Will be this change compatible with the old version of Pandas?
> 
> Thanks,
> 
> Fengchao

Hi，I have followed the instructions described above, including upgrade pandas and change the code(c01d623). now I got a different error "EasyPQP convert error END", and I got 7 results files now, but the quantification results are still missing. 

xueyang

-- done [took 0.02 s (CPU), 0.02 s (Wall)] -- 
Traceback (most recent call last):
  File "C:\Users\Xue\AppData\Local\Programs\Python\Python39\Scripts\easypqp-script.py", line 33, in <module>
    sys.exit(load_entry_point('easypqp==0.1.36', 'console_scripts', 'easypqp')())
  File "C:\Users\Xue\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Xue\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Xue\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1688, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Xue\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Xue\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Xue\AppData\Local\Programs\Python\Python39\lib\site-packages\easypqp\main.py", line 77, in convert
    psms, peaks = conversion(pepxmlfile, spectralfile, unimodfile, exclude_range, max_delta_unimod, max_delta_ppm, enable_unannotated, enable_massdiff, fragment_types, fragment_charges, enable_specific_losses, enable_unspecific_losses, max_psm_pep)
  File "C:\Users\Xue\AppData\Local\Programs\Python\Python39\lib\site-packages\easypqp\convert.py", line 667, in conversion
    peaks = read_mzml_or_mzxml_impl(spectralfile, psms[['scan_id', 'modified_peptide', 'precursor_charge']], theoretical, max_delta_ppm, 'mzml')
  File "C:\Users\Xue\AppData\Local\Programs\Python\Python39\lib\site-packages\easypqp\convert.py", line 436, in read_mzml_or_mzxml_impl
    input_map = {get_scan(e.getNativeID(), idx + 1): e for idx, e in enumerate(input_map.getSpectra())}
  File "pyopenms\pyopenms_5.pyx", line 4851, in pyopenms.pyopenms_5.MSExperiment.getSpectra
MemoryError: bad allocation
Traceback (most recent call last):
  File "C:\software\FragPipe-jre-19.1\fragpipe\tools\speclib\gen_con_spec_lib.py", line 980, in <module>
    main_easypqp()
  File "C:\software\FragPipe-jre-19.1\fragpipe\tools\speclib\gen_con_spec_lib.py", line 797, in main_easypqp
    assert all(p.returncode == 0 for p in procs)
AssertionError
exit status: 1
EasyPQP convert error END
Process 'SpecLibGen' finished, exit code: 1
Process returned non-zero exit code, stopping

**Comment by guoci** [comment]
@XueNotavailbale did you allocate enough memory? The previous log shows that you have 16G allocated. Try increasing that.

**Comment by XueNotavailbale** [comment]
> @XueNotavailbale did you allocate enough memory? The previous log shows that you have 16G allocated. Try increasing that.

Problem solved， Thanks a lot!! 
:)
