### ISSUE TITLE
MSBooster: External.KoinaModelCaller.assignMissingPeptidePredictions(KoinaModelCaller.java:465), Missing peptide to transfer prediction onto C[39.9950]TASDQVFLR 3: C[57.0215]TASDQVFLR|3

### ISSUE THREAD

**Issue by ClaSofMag** [Nesvilab/FragPipe#1692]
Hello,

I got an issue during the MSBooster process:

java.lang.NullPointerException
        at External.KoinaModelCaller.assignMissingPeptidePredictions(KoinaModelCaller.java:465)
        at Features.MainClass.main(MainClass.java:1301)
2024-07-25 15:31:44 [ERROR] - Missing peptide to transfer prediction onto C[39.9950]TASDQVFLR   3: C[57.0215]TASDQVFLR|3
2024-07-25 15:31:44 [ERROR] - Exiting now.

I used the same script with other samples and didn't get this error.

Thank you for your help

[meagre_plasma.7471.txt](https://github.com/user-attachments/files/16380473/meagre_plasma.7471.txt)

**Comment by yangkl96** [comment]
Hello,
Could you first try changing the Koina URL from `https\://koina.wilhelmlab.org\:443/v2/models/` to `https://koina.wilhelmlab.org:443/v2/models/`?

If that does not work, you can replace the old MSBooster with the one here:
https://www.dropbox.com/scl/fi/9v0men3eae218icysokfd/MSBooster-1.2.39.jar?rlkey=axfwxfbkxpec0fjl51htunaql&dl=0

**Comment by ClaSofMag** [comment]
Hello,

Thank you for your support. In fact the link in the workflow file it is correct, but in the log file it shows up like that, I don't know why. Anyway, I'm trying to run again, let's see.

**Comment by ClaSofMag** [comment]
I'm sorry but I got the same error. The thing is that I used exactly the same workflow, so same MSBooster, but in other samples and it worked. Here is that log file:

[meagre_mucus.7468.out.txt](https://github.com/user-attachments/files/16389678/meagre_mucus.7468.out.txt)

**Comment by yangkl96** [comment]
In your plasma samples, could you share the pin file that contains the peptide "C[39.9950]TASDQVFLR" that causes this error? Along with its associated mzml file. It may also appear as "C[-17" in the pin file

**Comment by yangkl96** [comment]
Could you also confirm for me that this is a DeepLC specific issue? For some subset of the files that worked, you can uncheck "find best RT model" and choose "Deeplc_hela_hf"

**Comment by ClaSofMag** [comment]
Both pin and mzML files are here: https://ualg365-my.sharepoint.com/:f:/g/personal/csraposo_ualg_pt/Er87xzIPoHxEtJ3jAI8BkQUBxjdeNl-mmhaua0yngxk_YQ?e=E73Jc4

**Comment by ClaSofMag** [comment]
Just finished with the new run, with "find beest RT model = false" and choosing the Deeplc_hela_hf and unfortunetly got exactly the same error

**Comment by yangkl96** [comment]
Thank you for your help troubleshooting. Could you also provide `/home/claudia/meagre/plasma/extreme_2/spectraRT.predicted.bin` and `/home/claudia/meagre/plasma/extreme_2/spectraRT_full.tsv`?

**Comment by ClaSofMag** [comment]
Hi yangkl96,
I don't know why but I haven't seen that part of the comment regarding the MSBooster update, but I tried now with it, and it worked perfectly.
I believe it is solved now.

Thank you for your support,

**Comment by yangkl96** [comment]
That is good to hear! I also noticed this issue in your log file that I could not reproduce, where MS2 models did not seem to be working correctly:
2024-07-25 13:05:45 [INFO] - Searching for best spectra model for your data
2024-07-25 13:05:45 [INFO] - Searching the following models: 
2024-07-25 13:05:45 [INFO] - [DIA-NN, ms2pip_2021_HCD, AlphaPept_ms2_generic, Prosit_2019_intensity, Prosit_2023_intensity_timsTOF, Prosit_2020_intensity_CID, Prosit_2020_intensity_TMT, Prosit_2020_intensity_HCD]
2024-07-25 13:05:47 [INFO] - Median similarity for DIA-NN is 0.0000
2024-07-25 13:05:49 [INFO] - Median similarity for ms2pip_2021_HCD is 0.0000
2024-07-25 13:05:49 [INFO] - Calibrating NCE
2024-07-25 13:05:56 [INFO] - Best NCE for AlphaPept_ms2_generic after calibration is 0
2024-07-25 13:05:56 [INFO] - Median similarity for AlphaPept_ms2_generic is 0.0000
2024-07-25 13:05:56 [INFO] - Calibrating NCE
2024-07-25 13:06:01 [INFO] - Best NCE for Prosit_2019_intensity after calibration is 0
2024-07-25 13:06:01 [INFO] - Median similarity for Prosit_2019_intensity is 0.0000
2024-07-25 13:06:01 [INFO] - Calibrating NCE
2024-07-25 13:06:06 [INFO] - Best NCE for Prosit_2023_intensity_timsTOF after calibration is 0
2024-07-25 13:06:06 [INFO] - Median similarity for Prosit_2023_intensity_timsTOF is 0.0000
2024-07-25 13:06:08 [INFO] - Median similarity for Prosit_2020_intensity_CID is 0.0000
2024-07-25 13:06:08 [INFO] - Calibrating NCE
2024-07-25 13:06:13 [INFO] - Best NCE for Prosit_2020_intensity_TMT after calibration is 0
2024-07-25 13:06:13 [INFO] - Median similarity for Prosit_2020_intensity_TMT is 0.0000
2024-07-25 13:06:13 [INFO] - Calibrating NCE
2024-07-25 13:06:18 [INFO] - Best NCE for Prosit_2020_intensity_HCD after calibration is 0
2024-07-25 13:06:18 [INFO] - Median similarity for Prosit_2020_intensity_HCD is 0.0000
2024-07-25 13:06:18 [INFO] - Spectra model chosen is 

Could you check that the models are not just returning `0.0000`? Or you can send the log for me to confirm

**Comment by ClaSofMag** [comment]
[meagre_plasma.7493.txt](https://github.com/user-attachments/files/16414060/meagre_plasma.7493.txt)
Thank you for checking that. Here is the log file of the last run

**Comment by yangkl96** [comment]
It looks like the MS2 prediction issue is still there. Could you share with me `/home/claudia/meagre/plasma/extreme_2/spectraRT.predicted.bin` please?

**Comment by ClaSofMag** [comment]
[spectraRT.predicted.zip](https://github.com/user-attachments/files/16414800/spectraRT.predicted.zip)
Here it is

**Comment by ClaSofMag** [comment]
[spectraRT.zip](https://github.com/user-attachments/files/16415100/spectraRT.zip)

**Comment by yangkl96** [comment]
Ok I have figured out the issue, it was that your search was using Daltons instead of ppm for fragment error tolerance. I have a fix here: https://www.dropbox.com/scl/fi/ctf0szodsap9zdupq1qxl/MSBooster-1.2.40.jar?rlkey=2nkuwms073noezwghtkzrd25w&dl=0

First you can enable both find best RT and spectra models. Then if you look at the Percolator weights, the `unweighted_spectral_entropy `weights will be much larger (~1-2) instead of near 0.

**Comment by yangkl96** [comment]
@ClaSofMag it should be shared with you now
