### ISSUE TITLE
FragPipe v23 and MSBooster error with timsTOF data

### ISSUE THREAD

**Issue by enonimos** [Nesvilab/FragPipe#2164]
**- Upload your log file**

[log_2025-05-03_22-35-18.zip](https://github.com/user-attachments/files/20028348/log_2025-05-03_22-35-18.zip)

**- Describe the issue or question:**

Hi FragPipe team, 
There are a ton of new features in v23, including the batch tab, this is great. Thank you for all your hard work and releasing this to the community!

I did a quick test with a few timsTOF files (dia and dda) and wanted to pass along a new issue I ran into. I get an error message in MSBooster when I enable any of the "Find best model" or select any of the AlphaPeptDeep models.  I've attached an representative error log from a dia-pasef run. This occurs with dda-pasef too.  I don't get the error message with ThermoRAW.

2025-05-03 22:35:18 [ERROR] - TIMSTOF is not a valid instrument for AlphaPeptDeep. Please use one of the following: [TIMSTOF, QE, SCIEXTOF, LUMOS].

Best,
Todd

**Comment by fcyu** [comment]
I think I have seen a similar error message during the testing stage. I thought we have fixed it.

Kevin @yangkl96 , can you take a look?

Thanks,

Fengchao

**Comment by anesvi** [comment]
Hi Todd, thanks for reporting the issue - you beat everyone else at finding and reporting a problem! You earn some bonus points from the FragPipe team!

**Comment by yangkl96** [comment]
Hi Todd,
Here is a link with a fixed MSBooster. Let me know if it works.
https://www.dropbox.com/scl/fi/aoy62sog3u5xgluusb2h5/MSBooster-1.3.10.jar?rlkey=joqg1oix9t7pv5e419aorjczt&st=gtq8yj56&dl=0

Thanks,
Kevin

**Comment by enonimos** [comment]
Hi Kevin,

The new MSBooster fixed the issue for me.

Thanks for quick reply,
Todd

**Comment by NaomiOsvl** [comment]
Hi all, 
I encountered avery similar problem using Astral data. I downloaded the new MSBooster version from your previous comment however, did not fix it nor did it crash. It continued printing 
"2025-05-12 16:02:02 [INFO] - THERMOTOF is not a valid instrument for AlphaPeptDeep. Please use one of the following: [TIMSTOF, QE, SCIEXTOF, LUMOS]
2025-05-12 16:02:02 [INFO] - Setting to QE for now."
over and over again, until I manually stopped it.
I have attached the log file. Do you have any suggestions? 

Best, 
Naomi

[log_2025-05-12_16-09-54.txt](https://github.com/user-attachments/files/20162767/log_2025-05-12_16-09-54.txt)

**Comment by yangkl96** [comment]
Hi Naomi,

Whoops this is definitely not ideal. Here's a new version with less verbosity: https://www.dropbox.com/scl/fi/mqrs72zv449xmagskhnun/MSBooster-1.3.11.jar?rlkey=qmlk8jaqcbt5j8c5ri4qlxvon&st=xvnlhiqu&dl=0

Currently no prediction model specifically supports Astral data, so we set the instrument metadata parameter to QE for now. 

Let me know if this fixes your problem,
Kevin

**Comment by yangkl96** [comment]
Glad to hear! It's good to see some testing with Astral data
